# Generated by Django 5.0.6 on 2024-06-02 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ticket')),
                ('titulo', models.CharField(choices=[('Instalação de Software', 'Instalação de Software'), ('Manutenção em Desktop', 'Manutenção em Desktop'), ('Upgrade de Software', 'Upgrade de Software'), ('Ativar Ponto de Rede', 'Ativar Ponto de Rede'), ('Outros', 'Outros')], max_length=40, verbose_name='Título')),
                ('departamento', models.CharField(choices=[('Planta', 'Planta'), ('Administrativo', 'Administrativo'), ('Recusros Humanos', 'Recusros Humanos'), ('Armazén', 'Armazén')], max_length=40, verbose_name='Departamento')),
                ('gerentes', models.CharField(choices=[('Lucas Fayad', 'Lucas Fayad'), ('Manoel Lucas', 'Manoel Lucas'), ('Lucas Tarias', 'Lucas Tarias'), ('Angelo Pickler', 'Angelo Pickler')], max_length=40, verbose_name='Gerente')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em andamento', 'Em andamento'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='chamados/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
