# Generated by Django 5.0.6 on 2024-06-02 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Chamado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='titulo',
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipodechamado',
            field=models.CharField(choices=[('Instalação de Software', 'Instalação de Software'), ('Manutenção em Desktop', 'Manutenção em Desktop'), ('Upgrade de Software', 'Upgrade de Software'), ('Ativar Ponto de Rede', 'Ativar Ponto de Rede'), ('Outros', 'Outros')], default=django.utils.timezone.now, max_length=40, verbose_name='Tipo de Chamado'),
            preserve_default=False,
        ),
    ]
