# Generated by Django 5.0.6 on 2024-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ativosgeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='Hostname')),
                ('vlan', models.CharField(choices=[('VLAN 10 - ProducServers', 'VLAN 10 - ProducServers'), ('VLAN 20 - Corp', 'VLAN 20 - Corp'), ('VLAN 42 - PBAPDV', 'VLAN 42 - PBAPDV'), ('VLAN 136 - Catraca e R. Ponto', 'VLAN 136 - Catraca e R. Ponto'), ('VLAN 132 - Câmera', 'VLAN 132 - Câmera'), ('VLAN 226 - Switch', 'VLAN 226 - Switch'), ('VLAN 228 - PTP', 'VLAN 228 - PTP')], max_length=40, verbose_name='VLAN')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address')),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('nserie', models.CharField(blank=True, max_length=50, null=True, verbose_name='N. Série')),
                ('fabricante', models.CharField(blank=True, choices=[('Cisco', 'Cisco'), ('Dell', 'Dell'), ('Ubiquiti', 'Ubiquiti'), ('DATACON', 'DATACON')], max_length=50, null=True, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=35, null=True, verbose_name='Modelo')),
                ('instaladoem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instalado em')),
                ('localidade', models.CharField(blank=True, choices=[('Antas Norte', 'Antas Norte'), ('Pedra Branca', 'Pedra Branca'), ('Centro Gold', 'Centro Gold'), ('Pantera', 'Pantera'), ('Ourilândia do Norte', 'Ourilândia do Norte')], max_length=50, null=True, verbose_name='Localidade')),
                ('categoria', models.CharField(choices=[('Rede', 'Rede'), ('Monitoramento', 'Monitoramento')], max_length=50, verbose_name='Categoria')),
                ('tipo', models.CharField(choices=[('Switch', 'Switch'), ('Acsses Point', 'Acsses Point'), ('NVR / DVR', 'NVR / DVR')], max_length=50, verbose_name='Tipo')),
                ('tipogestao', models.CharField(max_length=50, null=True, verbose_name='Tipo de Acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuário:')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha:')),
                ('obs', models.CharField(blank=True, max_length=60, null=True, verbose_name='Observações:')),
            ],
            options={
                'verbose_name': 'Ativos de Rede em Geral',
                'verbose_name_plural': 'Ativos de Rede em Geral',
            },
        ),
        migrations.CreateModel(
            name='Cisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='Hostname')),
                ('vlan', models.CharField(max_length=40, verbose_name='VLAN')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address')),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('nserie', models.CharField(blank=True, max_length=50, null=True, verbose_name='N. Série')),
                ('fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=35, null=True, verbose_name='Modelo')),
                ('instaladoem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instalado em')),
                ('localidade', models.CharField(max_length=50, verbose_name='Localidade')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('tipogestao', models.CharField(max_length=50, null=True, verbose_name='Tipo de Acesso')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuário:')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha:')),
                ('obs', models.CharField(blank=True, max_length=60, null=True, verbose_name='Observações:')),
            ],
            options={
                'verbose_name': 'CISCO',
                'verbose_name_plural': 'CISCO',
            },
        ),
        migrations.CreateModel(
            name='Dell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='Hostname')),
                ('vlan', models.CharField(max_length=40, verbose_name='VLAN')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address')),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('nserie', models.CharField(blank=True, max_length=50, null=True, verbose_name='N. Série')),
                ('fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=35, null=True, verbose_name='Modelo')),
                ('instaladoem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instalado em')),
                ('localidade', models.CharField(max_length=50, verbose_name='Localidade')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('tipogestao', models.CharField(max_length=50, null=True, verbose_name='Tipo de Acesso')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuário:')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha:')),
                ('obs', models.CharField(blank=True, max_length=60, null=True, verbose_name='Observações:')),
            ],
            options={
                'verbose_name': 'DELL',
                'verbose_name_plural': 'DELL',
            },
        ),
    ]
