# Generated by Django 5.0.6 on 2024-06-02 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosgeral',
            name='categoria',
            field=models.CharField(choices=[('REDE', 'REDE'), ('MONITORAMENTO', 'MONITORAMENTO'), ('COMUNICAÇÃO', 'COMUNICAÇÃO')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='fabricante',
            field=models.CharField(blank=True, choices=[('CISCO', 'CISCO'), ('DELL', 'DELL'), ('UBIQUITI', 'UBIQUITI'), ('DATACON', 'DATACON')], max_length=50, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='localidade',
            field=models.CharField(blank=True, choices=[('ANTAS NORTE', 'ANTAS NORTE'), ('PEDRA BRANCA', 'PEDRA BRANCA'), ('CENTRO GOLD', 'CENTRO GOLD'), ('PANTERA', 'PANTERA'), ('OURILÂNDIA DO NORTE', 'OURILÂNDIA DO NORTE')], max_length=50, null=True, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='tipo',
            field=models.CharField(choices=[('SWITCH', 'SWITCH'), ('ACSSES POINT', 'ACSSES POINT'), ('NVR / DVR', 'NVR / DVR')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='tipogestao',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Tipo de Acesso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='vlan',
            field=models.CharField(choices=[('VLAN 10 - FORMATAÇÃO', 'VLAN 10 - FORMATAÇÃO'), ('VLAN 20 - CORPORATIVO', 'VLAN 20 - CORPORATIVO'), ('VLAN 42 - PBAPDV', 'VLAN 42 - PBAPDV'), ('VLAN 136 - CATRACA E R. DE PONTO', 'VLAN 136 - CATRACA E R. DE PONTO'), ('VLAN 132 - CÂMERA', 'VLAN 132 - CÂMERA'), ('VLAN 226 - SWITCH', 'VLAN 226 - SWITCH'), ('VLAN 228 - PTP', 'VLAN 228 - PTP')], max_length=40, verbose_name='VLAN'),
        ),
    ]
