# Generated by Django 5.0.6 on 2024-06-02 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0002_alter_ativosgeral_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosgeral',
            name='fabricante',
            field=models.CharField(choices=[('CISCO', 'CISCO'), ('DELL', 'DELL'), ('UBIQUITI', 'UBIQUITI'), ('DATACON', 'DATACON')], default=django.utils.timezone.now, max_length=50, verbose_name='Fabricante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='instaladoem',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Instalado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='mac',
            field=models.CharField(max_length=50, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='nserie',
            field=models.CharField(max_length=50, verbose_name='N. Série'),
        ),
    ]
