# Generated by Django 5.0.6 on 2024-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0003_alter_ativosgeral_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosgeral',
            name='obs',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações:'),
        ),
    ]
