# Generated by Django 5.0.6 on 2024-06-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0006_rename_message_anotacoes_alter_anotacoes_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anotacoes',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
