# Generated by Django 5.0.6 on 2024-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0008_alter_message_created_at_alter_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=800, verbose_name='Insira suas Anotações'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Título'),
        ),
    ]
