# Generated by Django 5.0.6 on 2024-06-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0009_alter_message_content_alter_message_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Anotações', 'verbose_name_plural': 'Anotações'},
        ),
    ]
