# Generated by Django 5.0.6 on 2024-06-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0010_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='intelbras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='Hostname')),
                ('vlan', models.CharField(max_length=40, verbose_name='VLAN')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address')),
                ('mac', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('nserie', models.CharField(blank=True, max_length=50, null=True, verbose_name='N. Série')),
                ('fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=35, null=True, verbose_name='Modelo')),
                ('instaladoem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instalado em')),
                ('localidade', models.CharField(max_length=50, verbose_name='Localidade')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('tipogestao', models.CharField(max_length=50, null=True, verbose_name='Tipo de Acesso')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuário:')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha:')),
                ('obs', models.CharField(blank=True, max_length=60, null=True, verbose_name='Observações:')),
            ],
            options={
                'verbose_name': 'INTELBRAS',
                'verbose_name_plural': 'INTELBRAS',
            },
        ),
    ]
