# Generated by Django 5.0.6 on 2024-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0011_intelbras'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEDRABRANCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VLAN', models.CharField(blank=True, max_length=50, null=True, verbose_name='VLAN')),
                ('SERIAL', models.CharField(blank=True, max_length=50, null=True, verbose_name='N. Série')),
                ('SERVICE_TAG', models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Tag')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('IP', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Address')),
                ('HOSTNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hostname')),
                ('MAC', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('LOCAL', models.CharField(blank=True, max_length=50, null=True, verbose_name='Local')),
                ('SWITCH_PORT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Porta do Switch')),
            ],
            options={
                'verbose_name': 'DELL',
                'verbose_name_plural': 'DELL',
            },
        ),
        migrations.DeleteModel(
            name='Dell',
        ),
    ]
