# Generated by Django 5.0.6 on 2024-06-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0012_pedrabranca_delete_dell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedrabranca',
            options={'verbose_name': 'IP Network Schematic', 'verbose_name_plural': 'IP Network Schematic'},
        ),
    ]
