# Generated by Django 5.0.6 on 2024-06-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0013_alter_pedrabranca_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedrabranca',
            options={'verbose_name': 'Pedra Branca', 'verbose_name_plural': 'Pedra Branca'},
        ),
    ]
