# Generated by Django 5.0.6 on 2024-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0015_bhz'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedrabranca',
            name='MODEL_HOST',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MODEL / HOST'),
        ),
    ]
