# Generated by Django 5.0.6 on 2024-06-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0017_vlans'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VLAN', models.CharField(blank=True, max_length=50, null=True, verbose_name='VLAN')),
                ('SERIAL', models.CharField(blank=True, max_length=50, null=True, verbose_name='SERIAL')),
                ('SERVICE_TAG', models.CharField(blank=True, max_length=50, null=True, verbose_name='SERVICE TAG')),
                ('MODEL_HOST', models.CharField(blank=True, max_length=50, null=True, verbose_name='MODEL / HOST')),
                ('TYPE', models.CharField(blank=True, max_length=50, null=True, verbose_name='TYPE')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='NAME')),
                ('IP', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Address')),
                ('HOSTNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='HOSTNAME')),
                ('MAC', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('LOCAL_COMENT', models.CharField(blank=True, max_length=50, null=True, verbose_name='LOCAL (COMENT)')),
                ('SWITCH_PORT', models.CharField(blank=True, max_length=50, null=True, verbose_name='SWITCH PORT')),
                ('DHCP_OPTION', models.CharField(blank=True, max_length=50, null=True, verbose_name='DHCP OPTION')),
            ],
            options={
                'verbose_name': 'Pedra Branca',
                'verbose_name_plural': 'Pedra Branca',
            },
        ),
    ]
