# Generated by Django 5.0.6 on 2024-06-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0018_can'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='can',
            options={'verbose_name': 'CAN', 'verbose_name_plural': 'CAN'},
        ),
    ]
