# Generated by Django 5.0.6 on 2024-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0020_pantera_alter_bhz_options_alter_pedrabranca_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANTAS_NORTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VLAN', models.CharField(blank=True, max_length=50, null=True, verbose_name='VLAN')),
                ('SERIAL', models.CharField(blank=True, max_length=50, null=True, verbose_name='SERIAL')),
                ('SERVICE_TAG', models.CharField(blank=True, max_length=50, null=True, verbose_name='SERVICE TAG')),
                ('MODELO', models.CharField(blank=True, max_length=50, null=True, verbose_name='MODELO')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='NAME')),
                ('IP', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('HOSTNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='HOSTNAME')),
                ('MAC', models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC')),
                ('LOCAL', models.CharField(blank=True, max_length=50, null=True, verbose_name='LOCAL')),
                ('SWITCH_PORT', models.CharField(blank=True, max_length=50, null=True, verbose_name='SWITCH PORT')),
                ('COMMENTS', models.CharField(blank=True, max_length=50, null=True, verbose_name='COMMENTS')),
                ('DHCP', models.CharField(blank=True, max_length=50, null=True, verbose_name='DHCP')),
            ],
            options={
                'verbose_name': 'ANTAS NORTE',
                'verbose_name_plural': 'ANTAS NORTE',
            },
        ),
    ]
