# Generated by Django 5.0.6 on 2024-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0021_antas_norte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROUTES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='NAME')),
                ('VLAN', models.CharField(blank=True, max_length=50, null=True, verbose_name='VLAN')),
                ('VLAN_10', models.CharField(blank=True, max_length=50, null=True, verbose_name='10')),
                ('VLAN_20', models.CharField(blank=True, max_length=50, null=True, verbose_name='20')),
                ('VLAN_30', models.CharField(blank=True, max_length=50, null=True, verbose_name='30')),
                ('VLAN_31', models.CharField(blank=True, max_length=50, null=True, verbose_name='31')),
                ('VLAN_32', models.CharField(blank=True, max_length=50, null=True, verbose_name='32')),
                ('VLAN_42', models.CharField(blank=True, max_length=50, null=True, verbose_name='42')),
                ('VLAN_44', models.CharField(blank=True, max_length=50, null=True, verbose_name='44')),
                ('VLAN_132', models.CharField(blank=True, max_length=50, null=True, verbose_name='132')),
                ('VLAN_224', models.CharField(blank=True, max_length=50, null=True, verbose_name='224')),
                ('VLAN_226', models.CharField(blank=True, max_length=50, null=True, verbose_name='226')),
                ('VLAN_228', models.CharField(blank=True, max_length=50, null=True, verbose_name='228')),
                ('VLAN_236', models.CharField(blank=True, max_length=50, null=True, verbose_name='236')),
                ('VLAN_250', models.CharField(blank=True, max_length=50, null=True, verbose_name='250')),
                ('VLAN_251', models.CharField(blank=True, max_length=50, null=True, verbose_name='251')),
                ('INTERNET', models.CharField(blank=True, max_length=50, null=True, verbose_name='INTERNET')),
                ('COMENTARIOS', models.CharField(blank=True, max_length=50, null=True, verbose_name='COMENTÁRIOS')),
            ],
            options={
                'verbose_name': 'ROUTES',
                'verbose_name_plural': 'ROUTES',
            },
        ),
    ]
