# Generated by Django 5.0.6 on 2024-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0022_routes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='VLAN',
            new_name='VLAN01',
        ),
        migrations.AddField(
            model_name='routes',
            name='VLAN02',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VLAN'),
        ),
    ]
