# Generated by Django 5.0.6 on 2024-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0023_rename_vlan_routes_vlan01_routes_vlan02'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXTERNAL_IPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.CharField(blank=True, max_length=50, null=True, verbose_name='Site')),
                ('Provedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provedor')),
                ('Tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('IP_01', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('Rota_2', models.CharField(blank=True, max_length=50, null=True, verbose_name=' Rota 2')),
                ('IP_02', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('Gateway', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gateway')),
                ('Vlan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vlan')),
            ],
            options={
                'verbose_name': 'EXTERNAL IPs',
                'verbose_name_plural': 'EXTERNAL IPs',
            },
        ),
    ]
