# Generated by Django 5.0.6 on 2024-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0024_external_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATERIAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MATERIAL', models.CharField(blank=True, max_length=50, null=True, verbose_name='MATERIAL')),
                ('QTD', models.CharField(blank=True, max_length=50, null=True, verbose_name='QTD')),
                ('VENDOR', models.CharField(blank=True, max_length=50, null=True, verbose_name='VENDOR')),
                ('MODELO', models.CharField(blank=True, max_length=50, null=True, verbose_name='MODELO')),
                ('N_SERIE', models.CharField(blank=True, max_length=50, null=True, verbose_name='N/S')),
            ],
            options={
                'verbose_name': 'MATERIAL',
                'verbose_name_plural': 'MATERIAL',
            },
        ),
    ]
