# Generated by Django 5.0.6 on 2024-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0025_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosgeral',
            name='vlan',
            field=models.CharField(choices=[('VLAN 10 - FORMATAÇÃO', 'VLAN 10 - FORMATAÇÃO'), ('VLAN 20 - CORPORATIVO', 'VLAN 20 - CORPORATIVO'), ('VLAN 42 - PBAPDV', 'VLAN 42 - PBAPDV'), ('VLAN 136 - CATRACA E R. DE PONTO', 'VLAN 136 - CATRACA E R. DE PONTO'), ('VLAN 132 - CÂMERA', 'VLAN 132 - CÂMERA'), ('VLAN 226 - SWITCH', 'VLAN 226 - SWITCH'), ('VLAN 228 - PTP - ACSSES POINT', 'VLAN 228 - PTP - ACSSES POINT')], max_length=40, verbose_name='VLAN'),
        ),
    ]
