# Generated by Django 5.0.6 on 2024-06-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0026_alter_ativosgeral_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosgeral',
            name='ip',
            field=models.CharField(max_length=15, unique=True, verbose_name='IP Address'),
        ),
    ]
