# Generated by Django 5.0.6 on 2024-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0027_alter_ativosgeral_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACSSES_POINT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='Hostname')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='IP Address')),
                ('mac', models.CharField(max_length=50, unique=True, verbose_name='MAC')),
                ('vlan', models.CharField(choices=[('VLAN 10 - FORMATAÇÃO', 'VLAN 10 - FORMATAÇÃO'), ('VLAN 20 - CORPORATIVO', 'VLAN 20 - CORPORATIVO'), ('VLAN 42 - PBAPDV', 'VLAN 42 - PBAPDV'), ('VLAN 136 - CATRACA E R. DE PONTO', 'VLAN 136 - CATRACA E R. DE PONTO'), ('VLAN 132 - CÂMERA', 'VLAN 132 - CÂMERA'), ('VLAN 226 - SWITCH', 'VLAN 226 - SWITCH'), ('VLAN 228 - PTP - ACSSES POINT', 'VLAN 228 - PTP - ACSSES POINT')], max_length=40, unique=True, verbose_name='VLAN')),
                ('modelo', models.CharField(choices=[('01', 'UAP-AC-M-PRO'), ('02', 'UAP-AC-PRO'), ('03', 'UAP-AC-HD'), ('04', 'UAP-AC-LITE'), ('05', 'UAP-AC-U6-LITE'), ('06', 'UAP-AC-LR'), ('07', 'UAP-AC-U6-M'), ('08', 'UAP-AC-M')], max_length=50, unique=True, verbose_name='Modelo')),
                ('fabricante', models.CharField(choices=[('01', 'UBIQUITI'), ('02', 'CISCO'), ('03', 'TP-LINK'), ('04', 'D-LINK')], max_length=50, verbose_name='Fabricante')),
                ('instaladoem', models.CharField(max_length=50, verbose_name='Instalado em')),
                ('localidade', models.CharField(blank=True, choices=[('ANTAS NORTE', 'ANTAS NORTE'), ('PEDRA BRANCA', 'PEDRA BRANCA'), ('CENTRO GOLD', 'CENTRO GOLD'), ('PANTERA', 'PANTERA'), ('OURILÂNDIA DO NORTE', 'OURILÂNDIA DO NORTE')], max_length=50, null=True, verbose_name='Localidade')),
                ('tipo', models.CharField(choices=[('SWITCH', 'SWITCH'), ('ACSSES POINT', 'ACSSES POINT'), ('NVR / DVR', 'NVR / DVR')], max_length=50, verbose_name='Tipo')),
                ('obs', models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações:')),
            ],
            options={
                'verbose_name': 'ACSSES POINT',
                'verbose_name_plural': 'ACSSES POINT',
            },
        ),
    ]
