# Generated by Django 5.0.6 on 2024-06-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0030_alter_acsses_point_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsses_point',
            name='fabricante',
            field=models.CharField(choices=[('UBIQUITI', 'UBIQUITI'), ('CISCO', 'CISCO'), ('TP-LINK', 'TP-LINK'), ('D-LINK', 'D-LINK')], max_length=50, verbose_name='Fabricante'),
        ),
    ]
