# Generated by Django 5.0.6 on 2024-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0031_alter_acsses_point_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsses_point',
            name='modelo',
            field=models.CharField(choices=[('UAP-AC-M-Pro', 'UAP-AC-M-Pro'), ('UAP-AC-Pro', 'UAP-AC-Pro'), ('UAP-AC-HD', 'UAP-AC-HD'), ('UAP-AC-Lite', 'UAP-AC-Lite'), ('UAP-AC-U6-Lite', 'UAP-AC-U6-Lite'), ('UAP-AC-LR', 'UAP-AC-LR'), ('UAP-AC-U6-M', 'UAP-AC-U6-M'), ('UAP-AC-M', 'UAP-AC-M')], max_length=50, verbose_name='Modelo'),
        ),
    ]
