# Generated by Django 5.0.6 on 2024-06-07 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0032_alter_acsses_point_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsses_point',
            name='sitecontroller',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True, verbose_name='Site Controller'),
            preserve_default=False,
        ),
    ]
