# Generated by Django 5.0.6 on 2024-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0037_remove_acsses_point_sitecontroller'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsses_point',
            name='sitecontroller',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Site Controller'),
        ),
    ]
