# Generated by Django 5.0.6 on 2024-06-07 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0038_acsses_point_sitecontroller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsses_point',
            name='sitecontroller',
            field=models.CharField(choices=[('Oz-Homolog', 'Oz-Homolog'), ('PBA-MINA', 'PBA-MINA'), ('PBA-PRONTOS', 'PBA-PRONTOS'), ('Pedra Branca', 'Pedra Branca')], default=django.utils.timezone.now, max_length=30, verbose_name='Site Controller'),
            preserve_default=False,
        ),
    ]
