# Generated by Django 5.0.6 on 2024-06-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0040_alter_acsses_point_sitecontroller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsses_point',
            name='sitecontroller',
            field=models.CharField(choices=[('Oz-Homolog', 'Oz-Homolog'), ('PBA-MINA', 'PBA-MINA'), ('PBA-PRONTOS', 'PBA-PRONTOS'), ('Pedra Branca', 'Pedra Branca'), ('Antas Norte', 'Antas Norte'), ('Centro Gold', 'Centro Gold'), ('CAN - Exploration', 'CAN - Exploration')], max_length=30, verbose_name='Site na Controller'),
        ),
    ]
