# Generated by Django 5.0.6 on 2024-06-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0042_alter_acsses_point_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMERAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_ADDRESS', models.CharField(max_length=50, unique=True, verbose_name='IP Address')),
                ('N_CANAL', models.CharField(max_length=30, verbose_name='N. Canal')),
                ('PORTA', models.CharField(max_length=15, unique=True, verbose_name='Porta')),
                ('DISPOSITIVO_ID_CLOUD', models.CharField(max_length=50, unique=True, verbose_name='Dispositivo | ID Cloud')),
                ('FABRICANTE', models.CharField(max_length=40, verbose_name='Fabricante')),
                ('MODELO', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ADOTADO_EM', models.CharField(max_length=50, verbose_name='Adotado em:')),
                ('LOCAL', models.CharField(choices=[('ANTAS NORTE', 'ANTAS NORTE'), ('PEDRA BRANCA', 'PEDRA BRANCA'), ('CENTRO GOLD', 'CENTRO GOLD'), ('PANTERA', 'PANTERA'), ('OURILÂNDIA DO NORTE', 'OURILÂNDIA DO NORTE'), ('SANTA LUCIA', 'SANTA LUCIA')], max_length=50, verbose_name='Local')),
                ('OBS', models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações:')),
            ],
            options={
                'verbose_name': 'CAMERAS',
                'verbose_name_plural': 'CAMERAS',
            },
        ),
        migrations.AlterField(
            model_name='acsses_point',
            name='localidade',
            field=models.CharField(blank=True, choices=[('ANTAS NORTE', 'ANTAS NORTE'), ('PEDRA BRANCA', 'PEDRA BRANCA'), ('CENTRO GOLD', 'CENTRO GOLD'), ('PANTERA', 'PANTERA'), ('OURILÂNDIA DO NORTE', 'OURILÂNDIA DO NORTE'), ('SANTA LUCIA', 'SANTA LUCIA')], max_length=50, null=True, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='ativosgeral',
            name='localidade',
            field=models.CharField(blank=True, choices=[('ANTAS NORTE', 'ANTAS NORTE'), ('PEDRA BRANCA', 'PEDRA BRANCA'), ('CENTRO GOLD', 'CENTRO GOLD'), ('PANTERA', 'PANTERA'), ('OURILÂNDIA DO NORTE', 'OURILÂNDIA DO NORTE'), ('SANTA LUCIA', 'SANTA LUCIA')], max_length=50, null=True, verbose_name='Localidade'),
        ),
    ]
