# Generated by Django 5.0.6 on 2024-06-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0043_cameras_alter_acsses_point_localidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='PORTA',
            field=models.CharField(max_length=15, verbose_name='Porta'),
        ),
    ]
