# Generated by Django 5.0.6 on 2024-06-08 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0044_alter_cameras_porta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='IP_ADDRESS',
            field=models.CharField(error_messages={'invalid': 'Por favor, insira um endereço IP válido no formato 111.111.111.111.'}, max_length=15, unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='IP Address'),
        ),
    ]
