# Generated by Django 5.0.6 on 2024-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Inventario', '0045_alter_cameras_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.TextField()),
                ('field3', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
