# Generated by Django 5.0.6 on 2024-06-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_TeleLinhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhatelefonica',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_TeleLinhas.aparelhos', verbose_name='Linha Atribuida a'),
        ),
    ]
